var adjectives = [
  {
    type:'angry',
    values: [
      '',
      'Affronted',
      'Annoyed',
      'Antagonized',
      'Bitter',
      'Chafed',
      'Choleric',
      'Convulsed',
      'Cross',
      'Displeased',
      'Enraged',
      'Exacerbated',
      'Exasperated',
      'Ferocious',
      'Fierce',
      'Fiery',
      'Fuming',
      'Furious',
      'Galled',
      'Hateful',
      'Heated',
      'Hot',
      'Huffy',
      'Ill-tempered',
      'Impassioned',
      'Incensed',
      'Indignant',
      'Inflamed',
      'Infuriated',
      'Irascible',
      'Irate',
      'Ireful',
      'Irritable',
      'Irritated',
      'Maddened',
      'Nettled',
      'Offended',
      'Outraged',
      'Piqued',
      'Provoked',
      'Raging',
      'Resentful',
      'Riled',
      'Sore',
      'Splenetic',
      'Storming',
      'Sulky',
      'Sullen',
      'Tumultous/tumultuous',
      'Turbulent',
      'Uptight',
      'Vexed',
      'Wrathful'
    ]
  },
  {
    type:'fire',
    values: [
      '',
      'Afire',
      'Aflame',
      'Alight',
      'Blistering',
      'Broiling',
      'Conflagrant',
      'Enkindled',
      'Fiery',
      'Flaming',
      'Flaring',
      'Gleaming',
      'Glowing',
      'Heated',
      'Hot',
      'Ignited',
      'Illuminated',
      'In flames',
      'Incandescent',
      'Kindled',
      'On fire',
      'Oxidizing',
      'Red-hot',
      'Scorching',
      'Searing',
      'Sizzling',
      'Smoking',
      'Smouldering',
      'Torrid',
      'White-hot'
    ]
  },{
    type:'ice',
    values: [
      '',
      'Bitter',
      'Bleak',
      'Brisk',
      'Chilled',
      'Cool',
      'Crisp',
      'Frigid',
      'Frosty',
      'Frozen',
      'Icy',
      'Intense',
      'Raw',
      'Snowy',
      'Wintry',
      'Arctic',
      'Chill',
      'Cutting',
      'Hyperborean',
      'Icebox',
      'Keen',
      'Sharp',
      'Siberian',
      'Stinging',
      'Algid',
      'Below freezing',
      'Below zero',
      'Benumbed',
      'Biting',
      'Blasting',
      'Boreal',
      'Brumal',
      'Frore',
      'Gelid',
      'Glacial',
      'Has goose bumps',
      'Hawkish',
      'Hiemal',
      'Iced',
      'Inclement',
      'Nipping',
      'Nippy',
      'Numbed',
      'Numbing',
      'One-dog night',
      'Penetrating',
      'Piercing',
      'Polar',
      'Rimy',
      'Severe',
      'Shivery',
      'Sleety',
      'Snappy',
      'Two-dog night'
    ]
  },{
    type: 'ice',
    values:[
        'Blue',
        'Red',
        'Green',
        'Yellow',
        'Silver',
        'Ruby',
        'Diamond',
        'Gold',
        'Rainbow'
    ]
  },{
    type: 'silly',
    values:[
      '',
      'Ambiguous',
      'Ambidextrous',
      'Cunning',
      'Crazed',
      'Dopey',
      'Dozey',
      'Disingenuous',
      'Sleepy',
      'Frisky',
      'Horny',
      'Sexy',
      'Entitled',
      'Alienated',
      'Ascetic',
      'Asocial',
      'Austere',
      'Cynical',
      'Eremetic',
      'Hermitlike',
      'Frowning',
      'Introverted',
      'Misanthropic',
      'Reclusive',
      'Remote',
      'Reserved',
      'Retiring',
      'Solitary',
      'Standoffish',
      'Uncommunicative',
      'Unfriendly',
      'Unsociable',
      'Withdrawn',
      'Quarrelsome',
      'Grouchy',
      'Antisocial',
      'Silent'
    ]
  },{
    type:'misc',
    values: [
      '',
      'Glowing',
      'Radioactive',
      'Rusty',
      'Unkown',
      'Renowned',
      'Forgotten',
      'Ghostly',
      'Deathly',
      'Ghastly'
    ]
  }
];

var nouns = [
  'Augur',
  'Beast','Beastman','Basilisk','Brownie','Bunny','Banshee','Basilisk','Bookworm',
  'Creature','Cockatrice','Cyclops','Clown',
  'Dragon','Demon','Devil','Drake','Dinosaur',
  'Elemental',
  'Fae','Fox','Fiend','Foe',
  'Girl Guide','Ghost','Ghool','Ghast','Griffin','Gamer','Geek','Giant','Golem',
  'Harpy','Hag','Hug',
  'Insectoid','Incubus','Imp',
  'Jelly',
  'Kraken','Kobold','King',
  'Lion','Luggage','Lycanthrope','Lich','Lord',
  'Mouse','Mimic','Minotaur','Mech','Man',
  'Nargle','Naga','Nerd',
  'Octopusssssss','Ogre','Orc','Old Man',
  'Phoenix','Pingu','Plant',
  'Quadcopter',
  'Rancor','Robot',
  'Serpant','Spider','Scientist','Sandwich','Scout','Sphinx','Succubus','Siren','Sasquatch',
  'Toaster','Trump','Teacher','Troll',
  'Unicorn',
  'Vole','Vibrator','Vampire',
  'Witch','Wolf','Wyvern',
  'X',
  'Yeti',
  'Zombie'
];

module.exports = {
  find_random :  function(){
    var adjective_type = Math.floor(Math.random() * adjectives.length);
    var adjective = Math.floor(Math.random() * adjectives[adjective_type].values.length);
    var noun = Math.floor(Math.random() * nouns.length);

    return adjectives[adjective_type].values[adjective] + ' ' + nouns[noun];
  }
}
